# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Alexander Kazancev <kazancas@gmail.com>, 2011
# AlexL <loginov.alex.valer@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: fwbackups\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-12-30 02:23+0300\n"
"PO-Revision-Date: 2017-09-22 11:45+0000\n"
"Last-Translator: AlexL <loginov.alex.valer@gmail.com>\n"
"Language-Team: Russian (http://www.transifex.com/Magic/fwbackups/language/ru/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ru\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);\n"

#: ../test.operations.py:38
msgid "*** Initializing files"
msgstr "*** Инициализация файлов"

#: ../test.operations.py:41
#, python-format
msgid ""
"Folder %s exists and will be emptied. Press <Enter> to confirm or <ctrl+c> "
"to cancel..."
msgstr "Папка %s существует и должна быть очищена. Нажмите <Enter> для подтверждения или <ctrl+c> для отмены..."

#: ../test.operations.py:47
#, python-format
msgid "Cleaning folder %s..."
msgstr "Очистка папки %s..."

#: ../test.operations.py:57
msgid "*** Remote settings"
msgstr "*** Удалённые настройки"

#: ../test.operations.py:58
msgid "Hostname [localhost]: "
msgstr "Имя хоста [localhost]:"

#: ../test.operations.py:60
msgid "Port [22]: "
msgstr "Порт [22]:"

#: ../test.operations.py:65
msgid "The port field can only contain numbers. Please try again."
msgstr "Поле Порт может содержать только число. Введите заново."

#: ../test.operations.py:66
#, python-format
msgid "Username [%s]: "
msgstr "Имя пользователя [%s]:"

#: ../test.operations.py:67
msgid "Password: "
msgstr "Пароль:"

#: ../test.operations.py:68
#, python-format
msgid "Remote folder [%s]: "
msgstr "Удалённая папка [%s]:"

#: ../test.operations.py:96
#, python-format
msgid "*** Running %(a)s backup with engine %(b)s"
msgstr "*** Запуск %(a)s резервирования на движке %(b)s"

#: ../test.operations.py:107
msgid "Backup failed!"
msgstr "Сбой создания резервной копии!"

#: ../test.operations.py:124
#, python-format
msgid "*** Running restore of remote test backup %s"
msgstr "*** Запуск восстановления внешней тестовой копии %s"

#. fmt: Backup-SetName from Backup-Setname-2009-03-22_20-46[.tar[.gz|.bz2]]
#: ../test.operations.py:135 ../test.operations.py:165
#: ../src/fwbackups-runapp.py:1743 ../src/fwbackups-runapp.py:1806
#: ../src/fwbackups-runapp.py:1812 ../src/fwbackups/operations/backup.py:457
#: ../src/fwbackups/operations/backup.py:527
#: ../src/fwbackups/operations/backup.py:632
msgid "Backup"
msgstr "Резервная копия"

#: ../test.operations.py:147 ../test.operations.py:176
#: ../test.operations.py:201 ../test.operations.py:226
#: ../test.operations.py:257 ../test.operations.py:288
msgid "Restore failed!"
msgstr "Восстановление не удалось!"

#: ../test.operations.py:160
#, python-format
msgid "*** Running restore of local test backup %s"
msgstr "*** Запуск восстановления локальной тестовой копии %s"

#. Local archive
#: ../test.operations.py:180
msgid "*** Running restore of a local archive"
msgstr "*** Запуск восстановления локального архива"

#. Local folder
#: ../test.operations.py:205
msgid "*** Running restore of a local folder"
msgstr "*** Запуск восстановления локальной папки"

#. Remote archive (SSH)
#: ../test.operations.py:230
msgid "*** Running restore of a remote archive (SSH)"
msgstr "*** Запуск восстановления внешнего архива  (SSH)"

#. Remote folder (SSH)
#: ../test.operations.py:261
msgid "*** Running restore of a remote folder (SSH)"
msgstr "*** Запуск восстановления внешней папки (SSH)"

#: ../bin/fwbackups-run.py:40 ../bin/fwbackups-runonce.py:39
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"

#: ../bin/fwbackups-run.py:41 ../bin/fwbackups-runonce.py:40
msgid "Run with --help for usage information."
msgstr "Запустите с --help для получения дополнительной информации."

#: ../bin/fwbackups-run.py:43
msgid ""
"Usage: fwbackups-run [OPTIONS] Set_Name(s)\n"
"Options:\n"
"  -v, --verbose  :  Increase verbosity (print debug messages)\n"
"  -h, --help  :  Print this message and exit\n"
"  -l, --silent  :  Print messages to log file only\n"
"\n"
"Set_Name(s) is space-seperated list of set names to run backups of."
msgstr "Использование: fwbackups-run [параметры] имена_наборов\nПараметры:\n  -v, --verbose  : Выдать больше информации (печать сообщения дебагинга)\n  -h, --help  :  Напечатать это сообщение и выйти\n  -l, --silent  :  Выводить сообщения только в файл журнала\n\nИмена_наборов представляют собой заданные через пробел наборы для резервирования."

#: ../bin/fwbackups-run.py:95
msgid "Invalid usage: Requires at least one set name to backup"
msgstr "Неверное использование: Требуется как минимум одно имя конфигурации для резервирования"

#: ../bin/fwbackups-run.py:112
#, python-format
msgid "The set configuration for '%s' was not found - skipping."
msgstr "Настройки набора для '%s' не найдены - пропуск."

#: ../bin/fwbackups-run.py:122 ../bin/fwbackups-runonce.py:182
msgid "An error occurred while initializing the backup operation!"
msgstr "Ошибка при инициализации операции резервирования!"

#. thread returned
#: ../bin/fwbackups-run.py:132 ../bin/fwbackups-runonce.py:192
#: ../src/fwbackups-runapp.py:2510 ../src/fwbackups-runapp.py:2667
#: ../src/fwbackups-runapp.py:2753
#, python-format
msgid "Thread returned with retval %s"
msgstr "Поток вернул ошибку %s"

#: ../bin/fwbackups-run.py:134 ../bin/fwbackups-runonce.py:194
#: ../src/fwbackups-runapp.py:2515 ../src/fwbackups-runapp.py:2672
#: ../src/fwbackups/operations/backup.py:729
msgid "There was an error while performing the backup!"
msgstr "Ошибка при выполнении резервирования!"

#: ../bin/fwbackups-runonce.py:42
msgid ""
"Usage: fwbackups-runonce --destination-type=TYPE --engine=ENGINE [OPTIONS] Path(s) Destination\n"
"Options:\n"
"  -v, --verbose  :  Increase verbosity (print debug messages)\n"
"  -h, --help  :  Print this message and exit\n"
"  -r, --recursive  :  Perform a recursive backup\n"
"  -i, --hidden  :  Include hidden files in the backup\n"
"  -p, --packages2file  :  Print installed package list to a text file\n"
"  -d, --diskinfo2file  :  Print disk geometry to a file (must be root)\n"
"  -s, --sparse  :  Handle sparse files efficiently\n"
"  -e, --engine=ENGINE  :  Use specified backup engine.\n"
"              Valid engines are tar, tar.gz, tar.bz2 and rsync.\n"
"  -x, --exclude='PATTERN'  :  Skip files matching PATTERN.\n"
"  -n, --nice=NICE  :  Indicate the niceness of the backup process (-20 to 19)\n"
"  --destination-type=TYPE  :  Destination type (`local' or `remote (ssh)')\n"
"  --remote-host=HOSTNAME  :  Connect to remote host `HOSTNAME'\n"
"  --remote-user=USERNAME  :  Connect as specified username\n"
"  --remote-password=PASSWORD  :  Connect using password `PASSWORD'\n"
"  --remote-port=PORT  :  Connect on specified port (default 22)\n"
"\n"
"Path(s) is space-seperated list of paths to include in the backup.\n"
"Destination is the directory where the OneTime backup should be placed within.\n"
"\n"
"Defaults to tar engine and local destination unless specified otherwise.\n"
"Supplying --remote* will have no effect unless thedestination type is\n"
"`remote (ssh)'."
msgstr "Использование: wbackups-runonce --destination-type=ТИП --engine=ДВИЖОК [ПАРАМЕТРЫ] Путь(Пути) Назначение\nПараметры:\n  -v, --verbose  : Выдать больше информации (печать сообщения дебагинга)\n  -h, --help  :  Напечатать это сообщение и выйти\n  -r, --recursive  :  Выполнить рекурсивное резервирование\n  -i, --hidden  :  Включить в резервную копию скрытые файлы\n  -p, --packages2file  :  Вывести список установленных пакетов в текстовый файл\n  -d, --diskinfo2file  :  Вывести геометрию диска в файл (должны быть права root)\n  -s, --sparse  :  Более эффективно поддерживать разреженные файлы\n  -e, --engine=ДВИЖОК  :  Использовать определенный движок резервирования.\n              Доступны следующие движки: tar, tar.gz, tar.bz2 и rsync.\n  -x, --exclude='МАСКА'  :  Пропустить файлы, совпадающие с  МАСКОЙ.\n  -n, --nice=NICE  :  задать nice для процесса резервирования (от -20 до 19)\n  --destination-type=ТИП  :  Тип назначения (`local' или `remote (ssh)')\n  --remote-host=ИМЯ_ХОСТА  : Подключиться к удалённому хосту с именем `ИМЯ_ХОСТА'\n  --remote-user=ИМЯ_ПОЛЬЗОВАТЕЛЯ :  Подключиться под определённым пользователем\n  --remote-password=ПАРОЛЬ : Подключиться с использованием пароля `ПАРОЛЬ\n  --remote-port=PORT  :  Подключиться к заданному порту (по умолчанию 22)\n\nПуть(пути) - пути для резервирования через пробел.\nНазначение - папка, где должна быть помещена Одномоментная резервная копия.\n\nПо умолчанию в качестве движка используется tar и локальное расположение копии.\nПараметры удалённого сервера не будут применены, пока назначение не будет установлено в\n`remote (ssh)'."

#: ../bin/fwbackups-runonce.py:128
#, python-format
msgid "No such engine `%s'"
msgstr "Нет такого движка: `%s'"

#: ../bin/fwbackups-runonce.py:135
msgid "You must be root to set a niceness below 0"
msgstr "Вы должны иметь права root для nice ниже 0"

#: ../bin/fwbackups-runonce.py:139
msgid "Nice value must be an integer between -20 and 19"
msgstr "Значение nice может быть числом от -20 до 19"

#: ../bin/fwbackups-runonce.py:155
msgid "Requires at least one path to backup and a destination"
msgstr "Требуется как минимум один путь для резервирования и назначение"

#: ../bin/fwbackups-runonce.py:169
msgid "Destination type was not specified"
msgstr "Тип назначения не определён"

#: ../bin/fwbackups-runonce.py:172
msgid "An engine was not specified"
msgstr "Не задан движок"

#: ../src/fwbackups-runapp.py:42
msgid "An error occurred while importing gtk/gobject."
msgstr "Ошибка при импорте gtk/gobject."

#: ../src/fwbackups-runapp.py:43
msgid "Please make sure you have a valid GTK+ Runtime Environment."
msgstr "Убедитесь, что у вас установлена нужная версия GTK+."

#: ../src/fwbackups-runapp.py:67
#, python-format
msgid "fwbackups bug report written saved at %s"
msgstr "Сообщение об ошибке fwbackups записано как %s"

#: ../src/fwbackups-runapp.py:72
msgid "Could not write bug report due to insufficient permissions."
msgstr "Невозможно записать сообщение об ошибке из-за недостатка прав."

#: ../src/fwbackups-runapp.py:84
msgid "Please install pycrypto (python-crypto)"
msgstr "Установите pycrypto (python-crypto)"

#: ../src/fwbackups-runapp.py:88
msgid "Please install paramiko (python-paramiko)"
msgstr "Установите paramiko (python-paramiko)"

#: ../src/fwbackups-runapp.py:206 ../src/fwbackups.glade.h:19
#, no-c-format, python-format
msgid "%s"
msgstr "%s"

#: ../src/fwbackups-runapp.py:210 ../src/fwbackups-runapp.py:1428
#: ../src/fwbackups-runapp.py:1531 ../src/fwbackups-runapp.py:1935
msgid "Idle"
msgstr "Ожидание"

#. Default progressbars...
#: ../src/fwbackups-runapp.py:215 ../src/fwbackups-runapp.py:1427
msgid "Click 'Backup Set Now' to begin"
msgstr "Нажмите 'Резервировать сейчас' для начала"

#: ../src/fwbackups-runapp.py:216
msgid "Click 'Start Backup' to begin"
msgstr "Нажмите \"Запуск резервирования\" для начала"

#: ../src/fwbackups-runapp.py:217
msgid "Click 'Start Restore' to begin"
msgstr "Нажмите 'Старт восстановления' для начала"

#. self.ui.splashProgress.set_text('%s%% complete: %s' % (percent, text))
#: ../src/fwbackups-runapp.py:235
#, python-format
msgid "<span size=\"small\">%s%% complete: %s</span>"
msgstr "<span size=\"small\">%s%% завершено: %s</span>"

#: ../src/fwbackups-runapp.py:256
msgid "Checking permissions"
msgstr "Проверка прав"

#: ../src/fwbackups-runapp.py:264
msgid "Could not setup the fwbackups configuration folder"
msgstr "Невозможно задать папку настроек fwbackups"

#: ../src/fwbackups-runapp.py:265 ../src/fwbackups-runapp.py:304
#, python-format
msgid "The following error occured: %s"
msgstr "Произошла следующая ошибка: %s"

#. Step 2: Setup the logger
#: ../src/fwbackups-runapp.py:268
msgid "Setting up the logger and user preferences"
msgstr "Настройка журнала и прав пользователя"

#: ../src/fwbackups-runapp.py:272
#, python-format
msgid "Validation error: %s"
msgstr "Ошибка проверки: %s"

#: ../src/fwbackups-runapp.py:273
msgid "Preferences could not be read"
msgstr "Невозможно прочитать настройки"

#: ../src/fwbackups-runapp.py:273
msgid ""
"The preferences file may be corrupted and could not be read by fwbackups. "
"Would you like to initialize a new one from the default values? If not, "
"fwbackups will exit."
msgstr "Файл настроек может быть повреждён или недоступен для чтения fwbackups. Вы хотите создать новый с настройками по умолчанию? Если нет, то fwbackups завершит работу."

#. Log size...
#: ../src/fwbackups-runapp.py:298
msgid "Populating the log viewer"
msgstr "Заполнение просмотрщика журнала"

#: ../src/fwbackups-runapp.py:303
msgid "Could not setup the logger"
msgstr "Невозможно настроить журналирование"

#: ../src/fwbackups-runapp.py:314
msgid ""
"pynotify was not found. Notifcations will not be displayed unless notify-"
"python/pynotify is installed."
msgstr "pynotify не найден. Оповещения не будут отображаться, пока не будет установлен notify-python/pynotify."

#: ../src/fwbackups-runapp.py:342
msgid "Cleaning after previous versions"
msgstr "Очистка после предыдущей версии"

#: ../src/fwbackups-runapp.py:349
msgid "Previous installation of fwbackups 1.42.x or older detected"
msgstr "Обнаружена предыдущая (1.42) или более старая версия fwbackups."

#: ../src/fwbackups-runapp.py:349
msgid ""
"Because of certain major changes in fwbackups, your configuration must be imported manually. To do this, run fwbackups as the root user and select <i>File > Import</i> from the menu to import your old configuration.\n"
"If this action is not completed, the backups from version 1.42.x <b>will not run automatically</b>.\n"
"<i>Tip: The 1.42.x configuration was stored in /etc/fwbackups</i>."
msgstr "Из-за некоторых серьезных изменений в fwbackups, ваша конфигурация должна быть импортированы вручную. Для этого надо запустить fwbackups от root выбрать <i> Файл > Импорт </i> из меню, чтобы импортировать ваши старые настройки.\nЕсли не сделать это, то резервные копии с версии 1.42.x <b>не будут запускаться автоматически </b>.\n<i>Совет: Конфигурация версии 1.42.x хранится в файле /etc/fwbackups</i>."

#: ../src/fwbackups-runapp.py:356
msgid "A backup of /etc/crontab could not be created"
msgstr "Резервная копия /etc/crontab не может быть создана"

#: ../src/fwbackups-runapp.py:356
msgid ""
"You may wish to edit /etc/crontab manually and remove any fwbackups-related "
"lines."
msgstr "Вы можете отредактировать etc/crontab и удалить строки, относящиеся к fwbackups."

#: ../src/fwbackups-runapp.py:357
msgid "Could not create a backup of /etc/crontab; refusing to clean up."
msgstr "Невозможно создать резервную копию  /etc/crontab; требуется очистка."

#: ../src/fwbackups-runapp.py:360
msgid "Cleaning up /etc/crontab from previous installation of fwbackups"
msgstr "Очистка /etc/crontab от предыдущей установки fwbackups"

#: ../src/fwbackups-runapp.py:369
#, python-format
msgid ""
"fwbackups was unable to clean up the system crontab: %s. You may wish to "
"edit /etc/crontab manually and remove any fwbackups-related lines."
msgstr "fwbackups не может очистить системный crontab: %s. Вы можете отредактировать etc/crontab и удалить строки, относящиеся к fwbackups."

#: ../src/fwbackups-runapp.py:370
msgid "Cleanup of the system crontab failed"
msgstr "Cбой очистки системного crontab"

#: ../src/fwbackups-runapp.py:372
msgid "Ready!"
msgstr "Готов!"

#: ../src/fwbackups-runapp.py:376
msgid "fwbackups administrator started"
msgstr "Запуск управления fwbackups"

#: ../src/fwbackups-runapp.py:400
msgid "Would you like to clean up the log file?"
msgstr "Вы хотите очистить файл журнала?"

#: ../src/fwbackups-runapp.py:400
#, python-format
msgid ""
"The log file is becoming large (%s). Would you like to clear it? This will "
"permanently remove all entries from the log."
msgstr "Файл журнала становится слишком большим (%s). Не хотите его очистить? Это уничтожит все записи в журнале."

#: ../src/fwbackups-runapp.py:558
#, python-format
msgid "Could not create notification: %s"
msgstr "Невозможно создать оповещение: %s"

#: ../src/fwbackups-runapp.py:591
msgid "Regenerating crontab"
msgstr "Регенерация crontab"

#: ../src/fwbackups-runapp.py:592
msgid "Please wait... Regenerating crontab"
msgstr "Подождите... Идет регенерация crontab"

#: ../src/fwbackups-runapp.py:606
#, python-format
msgid "Could not parse the configuration for set '%s'"
msgstr "Невозможно прочитать конфигурацию для набора '%s'"

#: ../src/fwbackups-runapp.py:607
#, python-format
msgid ""
"The set configuration file '%s' failed to validate, so it may not be "
"properly scheduled. Other sets are unaffected by this error."
msgstr "Файл конфигурации набора '%s'  не прошёл проверку, и поэтому не может быть верно повторён по расписанию. Другие настройки должны помочь обойти ошибку."

#: ../src/fwbackups-runapp.py:614
#, python-format
msgid ""
"Internal error: generated entry for set '%s' was not parsable. Please submit"
" a bug report."
msgstr "Внутренняя ошибка: сгенерированная запись для набора '%s' не разбираема. Отправьте сообщение об ошибке."

#: ../src/fwbackups-runapp.py:617
#, python-format
msgid "Could not schedule automated backups for set '%s'"
msgstr "Невозможно создать расписание автоматического резервирования для набора '%s'"

#: ../src/fwbackups-runapp.py:618
msgid ""
"fwbackups could not regenerate a crontab entry because an error occured:\n"
msgstr "fwbackups не может регенерировать запись crontab из-за ошибки:\n"

#: ../src/fwbackups-runapp.py:619
#, python-format
msgid ""
"%(a)s\n"
"\n"
"The crontab entry associated with the error was:\n"
"%(b)s"
msgstr "%(a)s\n\nЗапись crontab, ассоциированная с ошибкой, следующая:\n%(b)s"

#. After all is done, log an message
#: ../src/fwbackups-runapp.py:622
#, python-format
msgid "Saving set `%s' to the crontab"
msgstr "Запись набора `%s' в crontab"

#: ../src/fwbackups-runapp.py:632
#, python-format
msgid "Unable to write new crontab: %s"
msgstr "Не могу записать новую задачу crontab: %s"

#: ../src/fwbackups-runapp.py:633
msgid "Unable to save backup schedule to crontab"
msgstr "Невозможно записать расписание резервирования в crontab"

#: ../src/fwbackups-runapp.py:633
msgid ""
"There was an error saving the new backup schedule. A backup will be restored, however the changes made to the backup schedule may not have been correctly saved.\n"
"\n"
"If you see this message, please report a bug against fwbackups."
msgstr "Возникла ошибка при сохранении нового расписания резервного копирования. Резервная копия будет восстановлена, однако изменения, сделанные в расписании резервного копирования, могут быть сохранены некорректно.\n\nЕсли вы видите это сообщение, пожалуйста, сообщите об ошибке в fwbackups."

#: ../src/fwbackups-runapp.py:637
msgid ""
"A backup of the crontab was restored; the latest changes to the backup "
"schedule not have been saved."
msgstr "Резервная копия crontab восстановлена; последние изменения в расписание резервного копирования не были сохранены."

#: ../src/fwbackups-runapp.py:639
msgid "A backup of the crontab could not be restored"
msgstr "Резервная копия crontab не может быть восстановлена"

#: ../src/fwbackups-runapp.py:655
msgid "fwbackups is working"
msgstr "fwbackups работает"

#: ../src/fwbackups-runapp.py:656
msgid ""
"An operation is currently in progress. Would you like to cancel it and quit "
"anyways?"
msgstr "Операция всё ещё выполняется. Вы хотите её прервать и выйти?"

#: ../src/fwbackups-runapp.py:658
msgid "Please wait... Canceling operations"
msgstr "Подождите... Операция отменяется"

#: ../src/fwbackups-runapp.py:671
msgid "fwbackups detected more than one alive threads!"
msgstr "fwbackups обнаружил более одного живого потока!"

#: ../src/fwbackups-runapp.py:676
#, python-format
msgid "Closed dead Paramiko thread: %s"
msgstr "Закрыт умерший поток Paramiko: %s"

#. FIXME: Figure out how to kill other thread types. For now, just log.
#: ../src/fwbackups-runapp.py:679
#, python-format
msgid "Could not close thread %s!"
msgstr "Невозможно закрыть поток %s!"

#: ../src/fwbackups-runapp.py:680
msgid "Please submit a bug report and include this message."
msgstr "Отправьте сообщение об ошибке, включив в него данный текст."

#: ../src/fwbackups-runapp.py:689 ../src/fwbackups-runapp.py:2431
msgid "Could not save backup schedule"
msgstr "Не удалось сохранить расписание резервирования"

#: ../src/fwbackups-runapp.py:689
msgid ""
"fwbackups was unable to save the backup scheduling information to the "
"crontab. If you are using manual times entry in one of your sets, please "
"verify that all five fields are using the correct syntax."
msgstr "fwbackups не может записать расписание резервирования в crontab. Если вы используете ручное задание времени в одном из ваших наборов, убедитесь в правильном синтаксисе задания."

#. Shutdown logging & quit the GTK mainloop
#: ../src/fwbackups-runapp.py:691
msgid "fwbackups administrator closed"
msgstr "Управление fwbackups закрыто"

#: ../src/fwbackups-runapp.py:707
msgid "Creating thread"
msgstr "Создаётся поток"

#: ../src/fwbackups-runapp.py:708
msgid "testConnection(): Creating thread"
msgstr "testConnection(): Создание потока"

#: ../src/fwbackups-runapp.py:711
msgid "Attempting to connect"
msgstr "Попытка соединения"

#: ../src/fwbackups-runapp.py:715
#, python-format
msgid "testConnection(): Thread returning with retval %s"
msgstr "testConnection(): Поток вернул значение %s"

#: ../src/fwbackups-runapp.py:717
msgid "Success!"
msgstr "Успешно!"

#: ../src/fwbackups-runapp.py:717
#, python-format
msgid "fwbackups was able to connect and authenticate on '%s'."
msgstr "fwbackups успешно подключился и авторизовался на '%s'."

#: ../src/fwbackups-runapp.py:719
msgid "Remote destination is not usable"
msgstr "Удалённое назначение не может использоваться"

#: ../src/fwbackups-runapp.py:719
#, python-format
msgid ""
"The folder '%(a)s' on '%(b)s' either does not exist or it is not a folder. "
"Please verify your settings and try again."
msgstr "Папка '%(a)s' на '%(b)s' не существует или не является папкой. Проверьте настройки и попробуйте снова."

#: ../src/fwbackups-runapp.py:721 ../src/fwbackups-runapp.py:1711
msgid "Authentication failed"
msgstr "Сбой аутентификации"

#: ../src/fwbackups-runapp.py:721
#, python-format
msgid ""
"A connection to '%s' was established, but authentication failed. Please "
"verify the username and password and try again."
msgstr "Соединение с '%s' установлено, но аутенфикация не прошла. Проверьте имя пользователя и пароль."

#: ../src/fwbackups-runapp.py:723 ../src/fwbackups-runapp.py:727
#, python-format
msgid "A connection to '%s' could not be established"
msgstr "Соединение с '%s' не может быть установлено"

#: ../src/fwbackups-runapp.py:723
#, python-format
msgid "Error %(a)s: %(b)s"
msgstr "Ошибка %(a)s: %(b)s"

#: ../src/fwbackups-runapp.py:725
#, python-format
msgid "The server '%s' is not responding"
msgstr "Сервер  '%s' не отвечает"

#: ../src/fwbackups-runapp.py:725 ../src/fwbackups-runapp.py:1718
msgid "Please verify your settings and try again."
msgstr "Проверьте параметры и повторите ещё раз."

#: ../src/fwbackups-runapp.py:727
#, python-format
msgid "Error: %s. Please verify your settings and try again."
msgstr "Ошибка: %s. Проверьте ваши настройки и попробуйте снова."

#: ../src/fwbackups-runapp.py:729 ../src/fwbackups-runapp.py:1400
#: ../src/fwbackups-runapp.py:1723
msgid "Unexpected error"
msgstr "Произошла непредвиденная ошибка"

#: ../src/fwbackups-runapp.py:741
msgid "Select file(s)"
msgstr "Выберите файл(ы)"

#: ../src/fwbackups-runapp.py:742
msgid "Configuration files (*.conf)"
msgstr "Файлы конфигурации (*.conf)"

#: ../src/fwbackups-runapp.py:803
msgid "File Exists"
msgstr "Файл уже существует"

#: ../src/fwbackups-runapp.py:804
#, python-format
msgid "'%s.conf' already exists! Would you like to overwrite it?"
msgstr "'%s.conf' уже существует. Заменить его?"

#: ../src/fwbackups-runapp.py:810
#, python-format
msgid "Exported set `%(a)s' to `%(b)s'"
msgstr "Экспортирован набор `%(a)s' в `%(b)s"

#: ../src/fwbackups-runapp.py:815 ../src/fwbackups.glade.h:141
msgid "Export Sets"
msgstr "Экспорт наборов"

#: ../src/fwbackups-runapp.py:825
msgid "Sets exported"
msgstr "Наборы экспортированы"

#: ../src/fwbackups-runapp.py:825
msgid "The selected sets were exported successfully."
msgstr "Выбранные потоки успешно экспортированы."

#: ../src/fwbackups-runapp.py:853 ../src/fwbackups-runapp.py:1349
#: ../src/fwbackups-runapp.py:1367 ../src/fwbackups-runapp.py:1445
#: ../src/fwbackups-runapp.py:2485
msgid "No set has been selected"
msgstr "Нет выбранных наборов"

#: ../src/fwbackups-runapp.py:853
msgid "You must select a set to duplicate."
msgstr "Вы должны выбрать набор для дублирования."

#: ../src/fwbackups-runapp.py:858
msgid "_copy"
msgstr "_копирование"

#: ../src/fwbackups-runapp.py:1062
#, python-format
msgid "Could not remove fwbackup's session autostart regkey: %s"
msgstr "Невозможно удалить ключ реестра автозапуска сессии fwbackup  '%s'"

#: ../src/fwbackups-runapp.py:1067
#, python-format
msgid "Could not remove fwbackup's session autostart file: %s"
msgstr "Невозможно удалить файл автозапуска сессии fwbackups '%s'"

#: ../src/fwbackups-runapp.py:1086
#, python-format
msgid "Resetting preference '%(a)s' to 0"
msgstr "Сброс настройки  '%(a)s' в 0"

#: ../src/fwbackups-runapp.py:1091 ../src/fwbackups-runapp.py:1111
#: ../src/fwbackups-runapp.py:1212 ../src/fwbackups-runapp.py:1568
#: ../src/fwbackups-runapp.py:1946 ../src/fwbackups-runapp.py:1957
#: ../src/fwbackups-runapp.py:1968 ../src/fwbackups.glade.h:146
msgid "Select a Folder"
msgstr "Выбор папки"

#: ../src/fwbackups-runapp.py:1131 ../src/fwbackups-runapp.py:1229
#: ../src/fwbackups-runapp.py:1489 ../src/fwbackups-runapp.py:1494
#: ../src/fwbackups-runapp.py:1585 ../src/fwbackups-runapp.py:1777
#: ../src/fwbackups-runapp.py:1868 ../src/fwbackups-runapp.py:1905
#: ../src/fwbackups-runapp.py:2391 ../src/fwbackups-runapp.py:2396
msgid "Missing information"
msgstr "Отсутствует информация"

#: ../src/fwbackups-runapp.py:1132
msgid "Please enter a Pycron installation directory."
msgstr "Задайте папку установки Pycron."

#: ../src/fwbackups-runapp.py:1136
msgid "Configuration not found"
msgstr "Файл конфигурации не найден"

#: ../src/fwbackups-runapp.py:1137
msgid ""
"The pycron configuration file was not found in the directory entered. Please"
" ensure that pycron is installed in the selected installation folder and "
"that it contains either a pycron configuration file or the sample pycron "
"configuration."
msgstr "Файл конфигурации pycron не был найден в папке входа. Пожалуйста, убедитесь, что pycron установлен в выбранную папку установки, и что он содержит либо конфигурационный файл pycron, либо пример конфигурации pycron."

#: ../src/fwbackups-runapp.py:1229
msgid "Please complete the host, username, folder and port fields."
msgstr "Задайте сервер, имя пользователя, папку и порт."

#: ../src/fwbackups-runapp.py:1349
msgid "You must select a set to edit."
msgstr "Вы должны выбрать набор для редактирования."

#: ../src/fwbackups-runapp.py:1367
msgid "You must select a set to remove."
msgstr "Вы должны выбрать набор для удаления."

#: ../src/fwbackups-runapp.py:1369
#, python-format
msgid "Delete backup set '%s'?"
msgstr "Удалить набор резервирования '%s'?"

#: ../src/fwbackups-runapp.py:1369
msgid ""
"This action will permanently delete the backup set configuration. This "
"action does not delete any existing backups or files."
msgstr "Это действие полностью удалит настройку набора резервирования, но не затронет существующих резервных копий или файлов."

#: ../src/fwbackups-runapp.py:1377 ../src/fwbackups-runapp.py:1385
#, python-format
msgid ""
"An error occured while removing set `%(a)s':\n"
"%(b)s"
msgstr "Ошибка при удалении набора `%(a)s':\n%(b)s"

#: ../src/fwbackups-runapp.py:1378
#, python-format
msgid "Could not remove backup set '%s'"
msgstr "Невозможно удалить набор резервирования '%s'"

#: ../src/fwbackups-runapp.py:1386
#, python-format
msgid "Could not remove the automated backup schedule for set '%s'"
msgstr "Не могу удалить расписание автоматического резервирования для набора '%s'"

#: ../src/fwbackups-runapp.py:1390
#, python-format
msgid "Removing set `%s'"
msgstr "Удаление набора `%s'"

#: ../src/fwbackups-runapp.py:1400
#, python-format
msgid ""
"An unexpected error occured while attempting to obtain the selected set:\n"
"%s"
msgstr "Произошла непредвиденная ошибка при попытке получить выбранный набор:\n%s"

#: ../src/fwbackups-runapp.py:1445
msgid "You must select a set to restore."
msgstr "Вы должны выбрать набор для восстановления."

#: ../src/fwbackups-runapp.py:1489 ../src/fwbackups-runapp.py:2391
msgid "Please fill in the Folder field."
msgstr "Заполните поле Папка."

#: ../src/fwbackups-runapp.py:1494 ../src/fwbackups-runapp.py:2396
msgid "Please fill in the Host, Username, Port and Folder fields."
msgstr "Задайте сервер, имя пользователя, папку и порт."

#: ../src/fwbackups-runapp.py:1585 ../src/fwbackups-runapp.py:1777
#: ../src/fwbackups-runapp.py:1905
msgid "Please complete all of the host, username, folder and port fields."
msgstr "Задайте все поля: сервер, имя пользователя, папку и порт."

#: ../src/fwbackups-runapp.py:1609
msgid "Log cleared"
msgstr "Журнал очищен"

#: ../src/fwbackups-runapp.py:1614
msgid "Clear the old log entries?"
msgstr "Удалить старые записи журнала?"

#: ../src/fwbackups-runapp.py:1615
msgid "This action will permanently remove all log entries."
msgstr "Это действие полностью удалит все записи журнала."

#: ../src/fwbackups-runapp.py:1633
#, python-format
msgid "Log saved to file `%s'"
msgstr "Журнал записан в файл '%s'"

#: ../src/fwbackups-runapp.py:1708
msgid "Previous backups could not be found"
msgstr "Невозможно найти предыдущую резервную копию"

#: ../src/fwbackups-runapp.py:1709
#, python-format
msgid "The destination folder for set '%s' was not found."
msgstr "Папка назначения для набора '%s' не найдена."

#: ../src/fwbackups-runapp.py:1712
#, python-format
msgid ""
"fwbackups was unable to authenticate on the remote server. Please verify the"
" username and password for set '%s' and try again."
msgstr "fwbackups не может аутенфицироваться на удалённом сервере. Проверьте имя пользователя и пароль для набора '%s' и попробуйте снова."

#: ../src/fwbackups-runapp.py:1714 ../src/fwbackups-runapp.py:1720
msgid "Connection failed"
msgstr "Сбой подключения"

#: ../src/fwbackups-runapp.py:1715
#, python-format
msgid ""
"A connection to the server could not be established:\n"
"Error %(a)s: %(b)s\n"
"Please verify your settings and try again."
msgstr "Соединение с сервером не установлено:\nОшибка %(a)s: %(b)s\n Проверьте ваши настройки и попробуйте снова."

#: ../src/fwbackups-runapp.py:1717
msgid "Remote server is not responding"
msgstr "Удалённый сервер не доступен"

#: ../src/fwbackups-runapp.py:1721
#, python-format
msgid ""
"A connection to the server could not be established because an error occurred: %s\n"
"Please verify your settings and try again."
msgstr "Соединение с сервером не установлено из-за ошибки: %s\nПроверьте ваши настройки и попробуйте снова."

#: ../src/fwbackups-runapp.py:1735
#, python-format
msgid ""
"Error obtaining file listing in destination %(a)s:\n"
"%(b)s"
msgstr "Ошибка получения списка файлов в назначении %(a)s:\n%(b)s"

#: ../src/fwbackups-runapp.py:1736
#, python-format
msgid "Could not get a list of old backups for set '%s'"
msgstr "Невозможно получить список старых резервных копий для набора '%s'"

#: ../src/fwbackups-runapp.py:1736
msgid ""
"If the destination is on removable media such as an external hard disk, "
"please attach it and try again."
msgstr "Если назначение является съёмным носителем, таким как внешний жёсткий диск, подключите его и попробуйте снова."

#. We can't start a restore if there are no set dates
#: ../src/fwbackups-runapp.py:1746 ../src/fwbackups-runapp.py:1876
#: ../src/fwbackups-runapp.py:1877
msgid "No backups found"
msgstr "Не найдено резервных копий"

#: ../src/fwbackups-runapp.py:1810 ../src/fwbackups-runapp.py:1828
#: ../src/fwbackups-runapp.py:1838
msgid "Automated restore not supported"
msgstr "Автоматическое восстановление не поддерживается"

#: ../src/fwbackups-runapp.py:1810 ../src/fwbackups-runapp.py:1828
#: ../src/fwbackups-runapp.py:1838
msgid ""
"This backup set cannot be automatically restored because restoration of "
"Archive backups has not been implemented for systems with Python 2.4. Please"
" see the user guide for details on manual restoration."
msgstr "Этот набор резервирования не может быть автоматически восстановлен, потому что восстановление из архива не доступно на системах с Python 2.4. Прочитайте руководство пользователя по ручному восстановлению."

#: ../src/fwbackups-runapp.py:1868
msgid "Please select a backup date."
msgstr "Выберите дату резервирования."

#: ../src/fwbackups-runapp.py:1877
#, python-format
msgid ""
"The backup set '%s' does not have any stored backups yet! Choose another "
"set, or alternatively choose a different restore source."
msgstr "Набор восстановления '%s'  не имеет сохранённых копий. Выберите другой набор или другой источник восстановления."

#: ../src/fwbackups-runapp.py:1884 ../src/fwbackups-runapp.py:1895
msgid "Restore source"
msgstr "Восстановить источник"

#: ../src/fwbackups-runapp.py:1884
msgid "Please enter the location of the local archive."
msgstr "Задайте расположение локального архива."

#: ../src/fwbackups-runapp.py:1887
msgid "Wrong file type"
msgstr "Неверный тип файла"

#: ../src/fwbackups-runapp.py:1888
msgid ""
"The file you selected is not a supported archive.\n"
"Supported archives types are tar with no, gzip or bzip2 compression."
msgstr "Файл, выбранный вами, не является поддерживаемым архивом.\nТипы поддерживаемых архивов: tar без сжатия, gzip или bzip2 сжатие."

#: ../src/fwbackups-runapp.py:1895
msgid "Please enter the location of the local folder."
msgstr "Задайте расположение локальной папки."

#: ../src/fwbackups-runapp.py:1982 ../src/fwbackups-runapp.py:1985
msgid "Invalid set name"
msgstr "Неверное имя набора"

#: ../src/fwbackups-runapp.py:1982
msgid "Please enter a set name."
msgstr "Введите имя набора."

#: ../src/fwbackups-runapp.py:1985
msgid ""
"'temporary_name' is a reserved name. Please choose another name for the set."
msgstr "'temporary_name' - это зарезервированное имя. Выберите другое имя для набора."

#: ../src/fwbackups-runapp.py:1989
#, python-format
msgid "Overwrite settings for set '%s'?"
msgstr "Перезаписать настройки для набора '%s'?"

#: ../src/fwbackups-runapp.py:1990
msgid ""
"This will overwrite the stored settings with the current ones. Are you sure "
"you want to continue?"
msgstr "Это действие перезапишет сохранённые настройки на текущие. Вы хотите продолжить?"

#: ../src/fwbackups-runapp.py:2101
msgid "Error parsing configuration file"
msgstr "Ошибка разбора файла конфигурации"

#: ../src/fwbackups-runapp.py:2102
msgid "fwbackups will using the default times instead."
msgstr "fwbackups будет использовать время по умолчанию."

#: ../src/fwbackups-runapp.py:2115
#, python-format
msgid "Unknown destination type `%s'"
msgstr "Неизвестный тип назначения `%s'"

#: ../src/fwbackups-runapp.py:2318
msgid "Error creating the automated backup schedules"
msgstr "Ошибка создания расписания автоматического резервирования"

#: ../src/fwbackups-runapp.py:2319
#, python-format
msgid ""
"The crontab could not be written because an error occured:\n"
"%s"
msgstr "Сrontab не может быть записан из-за ошибки:\n%s"

#: ../src/fwbackups-runapp.py:2355 ../src/fwbackups/widgets.py:718
msgid "Parsing configuration files"
msgstr "Разбор файла конфигурации"

#: ../src/fwbackups-runapp.py:2364 ../src/fwbackups/widgets.py:724
#, python-format
msgid "Refusing to parse file `%s': configuration files must end in `.conf'"
msgstr "Сбой разбора файла `%s': файл конфигурации должен иметь расширение `.conf'"

#: ../src/fwbackups-runapp.py:2414
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s"
msgstr "Переименовать набор `%(a)s' в `%(b)s"

#: ../src/fwbackups-runapp.py:2416
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s failed: %(c)s"
msgstr "Переименование набора `%(a)s' в `%(b)s не удалось: %(c)s"

#: ../src/fwbackups-runapp.py:2417
#, python-format
msgid "Could not rename set '%(a)s' to '%(b)s'"
msgstr "Невозможно переименовать набор '%(a)s' в '%(b)s'"

#. creating a set
#: ../src/fwbackups-runapp.py:2423
#, python-format
msgid "Creating set `%s'"
msgstr "Создаётся набор `%s'"

#. editing a set
#: ../src/fwbackups-runapp.py:2427
#, python-format
msgid "Saving changes to set `%s'"
msgstr "Запись изменений в набор `%s'"

#: ../src/fwbackups-runapp.py:2431
msgid ""
"Your set configuration changes were saved, but fwbackups was unable to save "
"the backup scheduling information to the crontab. If you are using manual "
"times entry, please verify that all five fields are using the correct "
"syntax."
msgstr "Изменение настроек вашего набора были сохранены, но fwbackups не смог сохранить расписание резервирования в crontab. Если вы используете ручное задание времени, проверьте, чтобы все поля имели верный синтаксис."

#: ../src/fwbackups-runapp.py:2468 ../src/fwbackups-runapp.py:2632
#, python-format
msgid "[%(a)i/%(b)i] Backing up: %(c)s"
msgstr "[%(a)i/%(b)i] Резервирование: %(c)s"

#: ../src/fwbackups-runapp.py:2471 ../src/fwbackups-runapp.py:2635
#, python-format
msgid "[%(a)i/%(b)i] Backing up files... Please wait"
msgstr "[%(a)i/%(b)i] Резервируются файлы... Подождите"

#: ../src/fwbackups-runapp.py:2473 ../src/fwbackups-runapp.py:2637
msgid "Cleaning old backups"
msgstr "Очистка старых резервных копий"

#: ../src/fwbackups-runapp.py:2475 ../src/fwbackups-runapp.py:2639
msgid "Sending files to remote server"
msgstr "Отправка файлов на удалённый сервер"

#: ../src/fwbackups-runapp.py:2477 ../src/fwbackups-runapp.py:2641
msgid "Executing user command"
msgstr "Выполнение команды пользователя"

#: ../src/fwbackups-runapp.py:2485
msgid "You must select to initiate a manual set backup."
msgstr "Вы должны выбрать для начала заданный вручную набор."

#: ../src/fwbackups-runapp.py:2491 ../src/fwbackups-runapp.py:2650
#: ../src/fwbackups-runapp.py:2735
msgid "Initializing"
msgstr "Инициализация"

#: ../src/fwbackups-runapp.py:2493 ../src/fwbackups-runapp.py:2534
#: ../src/fwbackups-runapp.py:2539 ../src/fwbackups-runapp.py:2542
#: ../src/fwbackups-runapp.py:2652 ../src/fwbackups-runapp.py:2692
#: ../src/fwbackups-runapp.py:2697 ../src/fwbackups-runapp.py:2702
#: ../src/fwbackups-runapp.py:2737 ../src/fwbackups-runapp.py:2775
#: ../src/fwbackups-runapp.py:2781 ../src/fwbackups-runapp.py:2786
msgid "Status"
msgstr "Статус"

#: ../src/fwbackups-runapp.py:2493
#, python-format
msgid "Starting a set backup operation of '%(a)s'"
msgstr "Запуск операции резервирования для набора '%(a)s'"

#: ../src/fwbackups-runapp.py:2496 ../src/fwbackups-runapp.py:2555
#: ../src/fwbackups-runapp.py:2655 ../src/fwbackups-runapp.py:2715
#: ../src/fwbackups-runapp.py:2740 ../src/fwbackups-runapp.py:2798
msgid "Please wait..."
msgstr "Пожалуйста, подождите..."

#: ../src/fwbackups-runapp.py:2502 ../src/fwbackups-runapp.py:2659
#: ../src/fwbackups-runapp.py:2745
msgid "Working"
msgstr "Работает"

#. error
#: ../src/fwbackups-runapp.py:2519 ../src/fwbackups-runapp.py:2537
#: ../src/fwbackups-runapp.py:2676 ../src/fwbackups-runapp.py:2695
#: ../src/fwbackups-runapp.py:2759 ../src/fwbackups-runapp.py:2779
msgid "<span color=\"Red\">Error</span>"
msgstr "<span color=\"Red\">Ошибка</span>"

#: ../src/fwbackups-runapp.py:2520 ../src/fwbackups-runapp.py:2680
#, python-format
msgid "An error occurred while initializing the backup operation: %s"
msgstr "Ошибка при инициализации операции резервирования: %s"

#: ../src/fwbackups-runapp.py:2524 ../src/fwbackups-runapp.py:2681
msgid "Error initializing backup"
msgstr "Ошибка инициализации резервной копии"

#: ../src/fwbackups-runapp.py:2534
#, python-format
msgid "Finished the automatic backup operation of set `%(a)s'"
msgstr "Завершено автоматическое резервирование для набора `%(a)s'"

#: ../src/fwbackups-runapp.py:2535 ../src/fwbackups-runapp.py:2693
#: ../src/fwbackups-runapp.py:2776
msgid "<span color=\"dark green\">Operation complete</span>"
msgstr "<span color=\"dark green\">Операция завершена</span>"

#: ../src/fwbackups-runapp.py:2539
#, python-format
msgid ""
"An error occured while performing the automatic backup operation of set "
"`%(a)s'"
msgstr "Ошибка при выполнении автоматического резервирования для набора `%(a)s'"

#: ../src/fwbackups-runapp.py:2542
#, python-format
msgid "The automatic backup operation of set `%(a)s' was cancelled"
msgstr "Операция автоматического резервирования для набора `%(a)s' отменена"

#: ../src/fwbackups-runapp.py:2543 ../src/fwbackups-runapp.py:2703
#: ../src/fwbackups-runapp.py:2787
msgid "<span color=\"red\">Operation cancelled</span>"
msgstr "<span color=\"red\">Операция отменена</span>"

#: ../src/fwbackups-runapp.py:2544 ../src/fwbackups-runapp.py:2704
#: ../src/fwbackups-runapp.py:2788
msgid "Operation cancelled"
msgstr "Операция была отменена."

#: ../src/fwbackups-runapp.py:2556 ../src/fwbackups-runapp.py:2716
#: ../src/fwbackups-runapp.py:2799
msgid "Cancelling..."
msgstr "Отмена..."

#: ../src/fwbackups-runapp.py:2652
msgid "Starting a one-time backup operation"
msgstr "Запуск разового резервирования"

#: ../src/fwbackups-runapp.py:2692
msgid "Finished the one-time backup operation"
msgstr "Окончание разового резервирования"

#: ../src/fwbackups-runapp.py:2697
msgid "An error occured while performing the one-time backup operation"
msgstr "Ошибка при выполнении операции разового резервирования"

#: ../src/fwbackups-runapp.py:2702
msgid "The one-time backup operation was cancelled"
msgstr "Операция разового резервирования была отменена."

#. no "current file" yet
#: ../src/fwbackups-runapp.py:2727
msgid "Receiving files from remote server"
msgstr "Приём файлов с удалённого сервера"

#. we have a 'current file'
#: ../src/fwbackups-runapp.py:2729
#, python-format
msgid "Restoring: %s"
msgstr "Восстановление: %s"

#: ../src/fwbackups-runapp.py:2737
msgid "Starting a restore operation"
msgstr "Старт операции восстановления"

#: ../src/fwbackups-runapp.py:2755
msgid ""
"There was an error while performing the restore! Enable debug messages for "
"more information."
msgstr "Ошибка при выполнении восстановления! Включите сообщения дебаггинга для получения большей информации."

#: ../src/fwbackups-runapp.py:2762
#, python-format
msgid "An error occurred while initializing the restore operation: %s"
msgstr "Ошибка при инициализации операции восстановления: %s"

#: ../src/fwbackups-runapp.py:2763
msgid "Error initializing restore operation"
msgstr "Ошибка инициализации операции восстановления"

#: ../src/fwbackups-runapp.py:2775
msgid "Finished the restore operation"
msgstr "Операция восстановления завершена"

#: ../src/fwbackups-runapp.py:2781
msgid "An error occured while performing the restore operation"
msgstr "Ошибка при выполнении операции восстановления"

#: ../src/fwbackups-runapp.py:2786
msgid "The restore operation was cancelled"
msgstr "Операция восстановления была отменена."

#. Customize our help text for the pre-created options
#: ../src/fwbackups-runapp.py:2810
msgid "Show this program's version and exit"
msgstr "Вывести версию установленной программы и закончить работу"

#: ../src/fwbackups-runapp.py:2811
msgid "Show this help message and exit"
msgstr "Показать это сообщение и закончить работу"

#. Add custom options
#: ../src/fwbackups-runapp.py:2813
msgid "print log messages to the terminal. Use this option twice"
msgstr "Вывод сообщений журнала на терминал. Используйте этот параметр дважды"

#: ../src/fwbackups-runapp.py:2814
msgid "start GUI minimized in the system tray"
msgstr "Сворачивать программу в системный лоток"

#: ../src/fwbackups.glade.h:1
msgid "fwbackups"
msgstr "fwbackups"

#: ../src/fwbackups.glade.h:2
msgid "To start, click one of the buttons on the above or use the menus."
msgstr "Для запуска нажмите на указанные кнопки или используйте меню."

#: ../src/fwbackups.glade.h:3
msgid ""
"Please do not forget to check your fwbackups log regularly to be informed about any\n"
"errors and/or failed backup runs."
msgstr "Не забывайте регулярно проверять журнал fwbackups на предмет наличия сообщений\nоб ошибках и/или сбоях резервирования."

#: ../src/fwbackups.glade.h:5
msgid "[ set by runapp.py ]"
msgstr "[ набор через runapp.py ]"

#: ../src/fwbackups.glade.h:6
msgid "<b>Welcome</b>"
msgstr "<b>Добро пожаловать</b>"

#: ../src/fwbackups.glade.h:7
msgid "<i>Not Loaded</i>"
msgstr "<i>Не загружен</i>"

#: ../src/fwbackups.glade.h:8
msgid "Total backup sets:"
msgstr "Всего наборов резервирования:"

#: ../src/fwbackups.glade.h:9
msgid "Failed backup runs:"
msgstr "Ошибка запуска резервирования:"

#: ../src/fwbackups.glade.h:10
msgid "<b>Status</b>"
msgstr "<b>Статус</b>"

#: ../src/fwbackups.glade.h:11
msgid "<span size=\"large\" weight=\"bold\">Overview</span>"
msgstr "<span size=\"large\" weight=\"bold\">Обзор</span>"

#: ../src/fwbackups.glade.h:12
msgid "_New Set"
msgstr "_Новый набор"

#: ../src/fwbackups.glade.h:13
msgid "Ed_it Set"
msgstr "Редактировать набор"

#: ../src/fwbackups.glade.h:14
msgid "_Delete Set"
msgstr "Удалить набор"

#: ../src/fwbackups.glade.h:15
msgid "_Backup Set Now"
msgstr "_Резервировать сейчас"

#: ../src/fwbackups.glade.h:16
msgid "Re_store Set"
msgstr "Восстановить набор"

#: ../src/fwbackups.glade.h:17
msgid "_Finish"
msgstr "_Готово"

#: ../src/fwbackups.glade.h:20
msgid "Status:"
msgstr "Статус:"

#: ../src/fwbackups.glade.h:21
msgid "Backup progress:"
msgstr "Прогресс резервирования:"

#: ../src/fwbackups.glade.h:22
msgid "<span size=\"large\" weight=\"bold\">Backups Sets</span>"
msgstr "<span size=\"large\" weight=\"bold\">Наборы резервирования</span>"

#: ../src/fwbackups.glade.h:23
msgid "_Add File(s)"
msgstr "_Добавить файл(ы)"

#: ../src/fwbackups.glade.h:24
msgid "_Add Folder(s)"
msgstr "_Добавить папку(и)"

#: ../src/fwbackups.glade.h:25
msgid ""
"Local folder\n"
"Remote folder (SSH)"
msgstr "Локальная папка\nУдалённая папка (SSH)"

#: ../src/fwbackups.glade.h:27
msgid "_Browse..."
msgstr "_Обзор..."

#: ../src/fwbackups.glade.h:28
msgid "Folder:"
msgstr "Папка:"

#: ../src/fwbackups.glade.h:29
msgid "/folder"
msgstr "/папка"

#: ../src/fwbackups.glade.h:30
msgid "Host:"
msgstr "Сервер:"

#: ../src/fwbackups.glade.h:31
msgid "Username:"
msgstr "Имя пользователя:"

#: ../src/fwbackups.glade.h:32
msgid "Password:"
msgstr "Пароль:"

#: ../src/fwbackups.glade.h:33
msgid "_Test Settings"
msgstr "_Тест настроек"

#: ../src/fwbackups.glade.h:34
msgid "Hide password"
msgstr "Скрыть пароль"

#: ../src/fwbackups.glade.h:35
msgid "Port:"
msgstr "Порт:"

#: ../src/fwbackups.glade.h:36
msgid "Destination type:"
msgstr "Тип назначения:"

#: ../src/fwbackups.glade.h:37
msgid "Archive (files and folders are packed into a tar archive)"
msgstr "Архив (файлы и папки будут запакованы в tar архив)"

#: ../src/fwbackups.glade.h:38
msgid "Direct copy of the files and folders"
msgstr "Прямое копирование файлов и папок"

#: ../src/fwbackups.glade.h:39
msgid "Compress archive using"
msgstr "Упаковать в архив используя"

#: ../src/fwbackups.glade.h:40
msgid ""
"gzip: fast, lightweight\n"
"bzip2: slower, more efficient"
msgstr "gzip: быстро, не требует ресурсов\nbzip2: медленнее, большее сжатие"

#: ../src/fwbackups.glade.h:42
msgid "<b>Backup Format</b>"
msgstr "<b>Формат резервирования</b>"

#: ../src/fwbackups.glade.h:43
msgid "Enabled"
msgstr "Включен"

#: ../src/fwbackups.glade.h:44
msgid "Recursive"
msgstr "Рекурсивно"

#: ../src/fwbackups.glade.h:45
msgid "Print installed packages to a text file"
msgstr "Вывод установленных пакетов в файл"

#: ../src/fwbackups.glade.h:46
msgid "Print disk geometry information to a file"
msgstr "Вывод геометрии диска в файл"

#: ../src/fwbackups.glade.h:47
msgid "Include hidden files"
msgstr "Включая скрытые файлы"

#: ../src/fwbackups.glade.h:48
msgid "Handle sparse files efficiently"
msgstr "Эффективная поддержка разреженных файлов"

#: ../src/fwbackups.glade.h:49
msgid "Follow links"
msgstr "Следовать по ссылкам"

#: ../src/fwbackups.glade.h:50
msgid "<b>Backup Options</b>"
msgstr "<b>Параметры резервирования</b>"

#: ../src/fwbackups.glade.h:51
msgid ""
"Exclude from backup:\n"
" (newline separated)"
msgstr "Исключить из копии:\n(новый пункт в новой строке)"

#: ../src/fwbackups.glade.h:53
msgid "Nice value of backup process:"
msgstr "Значение nice для процесса резервирования:"

#: ../src/fwbackups.glade.h:54
msgid "<b>Advanced Options</b>"
msgstr "<b>Дополнительно</b>"

#: ../src/fwbackups.glade.h:55
msgid "_Back"
msgstr "_Назад"

#: ../src/fwbackups.glade.h:56
msgid "_Next"
msgstr "_Следующий"

#: ../src/fwbackups.glade.h:57
msgid "_Start Backup"
msgstr "_Запуск резервирования"

#: ../src/fwbackups.glade.h:58
msgid "<span size=\"large\" weight=\"bold\">One-Time Backup</span>"
msgstr "<span size=\"large\" weight=\"bold\">Разовое резервирование</span>"

#: ../src/fwbackups.glade.h:59
msgid "_Save to File"
msgstr "_Сохранить в файл"

#: ../src/fwbackups.glade.h:60
msgid "<span size=\"large\" weight=\"bold\">Log Viewer</span>"
msgstr "<span size=\"large\" weight=\"bold\">Просмотр журнала</span>"

#: ../src/fwbackups.glade.h:61
msgid "Overview"
msgstr "Обзор"

#: ../src/fwbackups.glade.h:62
msgid "Backup Sets"
msgstr "Наборы"

#: ../src/fwbackups.glade.h:63
msgid "One-Time Backup"
msgstr "Разовая копия"

#: ../src/fwbackups.glade.h:64
msgid "Log Viewer"
msgstr "Журнал"

#: ../src/fwbackups.glade.h:65
msgid "Restore"
msgstr "Восстановить"

#: ../src/fwbackups.glade.h:66
msgid "_File"
msgstr "_Файл"

#: ../src/fwbackups.glade.h:67
msgid "Create a new backup set"
msgstr "Создать новый набор резервирования"

#: ../src/fwbackups.glade.h:68
msgid "Import a set from a .conf file"
msgstr "Импортировать набор из .conf файла"

#: ../src/fwbackups.glade.h:69
msgid "_Import Sets"
msgstr "_Импорт наборов"

#: ../src/fwbackups.glade.h:70
msgid "Export one or more sets to .conf files"
msgstr "Экспортировать один или несколько наборов в .conf файл"

#: ../src/fwbackups.glade.h:71
msgid "E_xport Sets"
msgstr "_Экспорт наборов"

#: ../src/fwbackups.glade.h:72
msgid "_Edit"
msgstr "_Править"

#: ../src/fwbackups.glade.h:73
msgid "Edit the selected backup set"
msgstr "Редактировать выбранный набор"

#: ../src/fwbackups.glade.h:74
msgid "_Edit Set"
msgstr "_Править набор"

#: ../src/fwbackups.glade.h:75
msgid "Remove the selected backup set"
msgstr "Удалить выбранный набор резервирования"

#: ../src/fwbackups.glade.h:76
msgid "Duplicate the selected backup set"
msgstr "Скопировать выбранный набор"

#: ../src/fwbackups.glade.h:77
msgid "D_uplicate Set"
msgstr "_Дублировать набор"

#: ../src/fwbackups.glade.h:78
msgid "_View"
msgstr "_Вид"

#: ../src/fwbackups.glade.h:79
msgid "Switch to Overview"
msgstr "Переключиться в Обзор"

#: ../src/fwbackups.glade.h:80
msgid "_Overview"
msgstr "_Обзор"

#: ../src/fwbackups.glade.h:81
msgid "Switch to User Backup Sets"
msgstr "Переключить в Пользовательский набор резервирования"

#: ../src/fwbackups.glade.h:82
msgid "_Backup Sets"
msgstr "_Наборы для резервирования"

#: ../src/fwbackups.glade.h:83
msgid "Switch to One-Time Backup"
msgstr "Переключиться на Разовое резервирование"

#: ../src/fwbackups.glade.h:84
msgid "O_ne-Time Backup"
msgstr "_Разовое резервирование"

#: ../src/fwbackups.glade.h:85
msgid "Switch to Log Viewer"
msgstr "Переключиться в Просмотр журнала"

#: ../src/fwbackups.glade.h:86
msgid "_Log"
msgstr "_Журнал"

#: ../src/fwbackups.glade.h:87
msgid "Switch to Restore"
msgstr "Переключиться в Восстановление"

#: ../src/fwbackups.glade.h:88
msgid "_Restore"
msgstr "_Восстановить"

#: ../src/fwbackups.glade.h:89
msgid "_Help"
msgstr "_Справка"

#: ../src/fwbackups.glade.h:90
msgid "Check for _Updates"
msgstr "_Проверить обновления"

#: ../src/fwbackups.glade.h:91
msgid "About fwbackups"
msgstr "О fwbackups"

#: ../src/fwbackups.glade.h:92
msgid "<span color=\"blue\"><u>http://www.diffingo.com/opensource</u></span>"
msgstr "<span color=\"blue\"><u>http://www.diffingo.com/opensource</u></span>"

#: ../src/fwbackups.glade.h:93
msgid "<span size=\"small\">(C) 2005 - 2010 Stewart Adam</span>"
msgstr "<span size=\"small\">(C) 2005 - 2010 Stewart Adam</span>"

#: ../src/fwbackups.glade.h:95
#, no-c-format
msgid "<span size=\"xx-large\" weight=\"bold\">fwbackups %s</span>"
msgstr "<span size=\"xx-large\" weight=\"bold\">fwbackups %s</span>"

#: ../src/fwbackups.glade.h:96
msgid "<span size=\"large\"> A feature-rich user backup program</span>"
msgstr "<span size=\"large\"> Программа резервирования с продвинутыми настройками</span>"

#: ../src/fwbackups.glade.h:97
msgid ""
"    This program is free software; you can redistribute it and/or modify\n"
"    it under the terms of the GNU General Public License as published by\n"
"    the Free Software Foundation; either version 2 of the License, or\n"
"    (at your option) any later version.\n"
"\n"
"    This program is distributed in the hope that it will be useful,\n"
"    but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n"
"    See the GNU General Public License for more details.\n"
"\n"
"    You should have received a copy of the GNU General Public License\n"
"    along with this program; if not, write to the\n"
"    Free Software Foundation, Inc.,\n"
"    51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA\n"
msgstr "fwbackup - это свободная программа; вы можете распространять её\nи/или модифицировать в соответствии с лицензией\nGNU General Public License, которая опубликована\nFree Software Foundation; или версией 2 лицензии, или\n(по вашему желанию) любой поздней версией.\n\nfwbackup распространяется в надежде, что она будет полезна,\nно БЕЗ ЛЮБЫХ ГАРАНТИЙ; даже без подразумеваемой гарантии\nКОММЕРЧЕСКОЙ ЦЕННОСТИ или ПРИГОДНОСТИ ДЛЯ КОНКРЕТНЫХ ЦЕЛЕЙ.\nСмотрите GNU General Public License для подробностей.\n\nВы должны были получить копию GNU General Public License\nс программой; если нет, то напишите в Free Software\nFoundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA\n"

#: ../src/fwbackups.glade.h:112
msgid "License"
msgstr "Лицензия"

#: ../src/fwbackups.glade.h:113
msgid ""
"\n"
"Developers:\n"
"          Stewart Adam < s.adam@diffingo.com >\n"
"\n"
"Documenters:\n"
"          Stewart Adam < s.adam@diffingo.com >\n"
"\n"
"Translators:\n"
"\tN/A\n"
"\n"
"Graphic Designers:\n"
"\tStewart Adam < s.adam@diffingo.com >\n"
"        * Based on gnome-icon-theme icons\n"
msgstr "\nРазработчики:\n          Stewart Adam < s.adam@diffingo.com >\n\nДокументация:\n          Stewart Adam < s.adam@diffingo.com >\n\nПереводчики:\n\tАлександр Казанцев <kazancas@gmail.com>\n        Алексей Логинов <loginov.alex.valer@gmail.com>\n\nДизайн:\n\tStewart Adam < s.adam@diffingo.com >\n        * Основан на иконках gnome-icon-theme\n"

#: ../src/fwbackups.glade.h:127
msgid "Credits"
msgstr "Авторы"

#: ../src/fwbackups.glade.h:128
msgid "Select a file or folder"
msgstr "Выбор файла или папки"

#: ../src/fwbackups.glade.h:129
msgid ""
"<span size=\"larger\" weight=\"bold\">Primary text</span>\n"
"\n"
"Secondary text"
msgstr "<span size=\"larger\" weight=\"bold\">Основной текст</span>\n\nДополнительный текст"

#: ../src/fwbackups.glade.h:132
msgid "Don't show me this message again"
msgstr "Не показывать больше это сообщение"

#: ../src/fwbackups.glade.h:133
msgid "Save to..."
msgstr "Сохранение в..."

#: ../src/fwbackups.glade.h:134
msgid "Status: fwbackups is running"
msgstr "Статус: fwbackups запущен"

#: ../src/fwbackups.glade.h:135
msgid "_Show Administrator"
msgstr "_Показать окно управления"

#: ../src/fwbackups.glade.h:136
msgid "_Minimize to tray on close"
msgstr "_Минимизировать в сист. лоток при закрытии"

#: ../src/fwbackups.glade.h:137
msgid "Display _Notifications"
msgstr "Отображать уведомления"

#: ../src/fwbackups.glade.h:138
msgid "Edit preferences"
msgstr "Редактировать параметры"

#: ../src/fwbackups.glade.h:139
msgid "_Preferences"
msgstr "_Параметры"

#: ../src/fwbackups.glade.h:140
msgid "_Quit"
msgstr "_Выход"

#: ../src/fwbackups.glade.h:142
msgid "_Export"
msgstr "_Экспорт"

#: ../src/fwbackups.glade.h:143
msgid "Export to:"
msgstr "Экспорт в:"

#: ../src/fwbackups.glade.h:144
msgid "<span size=\"larger\" weight=\"bold\">Export Sets</span>"
msgstr "<span weight=\"bold\" size=\"larger\">Экспорт наборов</span>"

#: ../src/fwbackups.glade.h:145
msgid "Select the set you would like to export."
msgstr "Выбор наборов для экспорта."

#: ../src/fwbackups.glade.h:147
msgid "Restore Files"
msgstr "Восстановление файлов"

#: ../src/fwbackups.glade.h:148
msgid ""
"Set backup\n"
"Local archive\n"
"Local folder\n"
"Remote archive (SSH)\n"
"Remote folder (SSH)"
msgstr "Набор резервирования\nЛокальный архив\nЛокальная папка\nУдалённый архив (SSH)\nУдалённая папка (SSH)"

#: ../src/fwbackups.glade.h:153
msgid "Set:"
msgstr "Набор:"

#: ../src/fwbackups.glade.h:154
msgid "Date:"
msgstr "Дата:"

#: ../src/fwbackups.glade.h:155
msgid "Browse..."
msgstr "Обзор..."

#: ../src/fwbackups.glade.h:156
msgid "Archive:"
msgstr "Архив:"

#: ../src/fwbackups.glade.h:157
msgid "/"
msgstr "/"

#: ../src/fwbackups.glade.h:158
msgid "Location:"
msgstr "Расположение:"

#: ../src/fwbackups.glade.h:159
msgid "Test Settings"
msgstr "Тест настроек"

#: ../src/fwbackups.glade.h:160
msgid ""
"<i>Note: fwbackups will copy the remote backup to the disk first, then unpack it.\n"
"Please ensure enough disk space is available.</i>"
msgstr "<i>Примечание: fwbackups скопирует сначала удалённую резервную копию на диск, а затем разархивирует её.\nУбедитесь, что у вас достаточно места.</i>"

#: ../src/fwbackups.glade.h:162
msgid "Source type:"
msgstr "Тип источника:"

#: ../src/fwbackups.glade.h:163
msgid "Restore to:"
msgstr "Восстановить в:"

#: ../src/fwbackups.glade.h:164
msgid ""
"<i>Tip: entering '/' or selecting </i>'File System'<i> will restore files to"
" their original locations.</i>"
msgstr "<i>Совет: ввод '/' или выбор </i>'Файловая система'<i> восстановит файлы в их изначальное расположение.</i>"

#: ../src/fwbackups.glade.h:165
msgid "Restore Progress:"
msgstr "Прогресс восстановления:"

#: ../src/fwbackups.glade.h:166
msgid "Start _Restore"
msgstr "Запуск _восстановления"

#: ../src/fwbackups.glade.h:167
msgid "Preferences"
msgstr "Параметры"

#: ../src/fwbackups.glade.h:168
msgid "Minimize to tray on close"
msgstr "Сворачивать в системный лоток при закрытии"

#: ../src/fwbackups.glade.h:169
msgid "Show notifications in tray area"
msgstr "Показывать уведомления в системном лотке"

#: ../src/fwbackups.glade.h:170
msgid "Show tray icon"
msgstr "Показывать иконку в системном лотке"

#: ../src/fwbackups.glade.h:171
msgid "Start minimized"
msgstr "Запускать в свёрнутом виде"

#: ../src/fwbackups.glade.h:172
msgid "<b>Tray Options</b>"
msgstr "<b>Параметры сист. лотка</b>"

#: ../src/fwbackups.glade.h:173
msgid "Always show debug messages in the log"
msgstr "Всегда показывать сообщения дебагинга в журнале"

#: ../src/fwbackups.glade.h:174
msgid "Start fwbackups (minimized) when I login"
msgstr "Запускать fwbackups (свернув) при каждом входе"

#: ../src/fwbackups.glade.h:175
msgid "Customize temporary directory"
msgstr "Настроить временную папку"

#: ../src/fwbackups.glade.h:176
msgid "<b>Misc. Options</b>"
msgstr "<b>Разное</b>"

#: ../src/fwbackups.glade.h:177
msgid "Pycron installation directory:"
msgstr "Папка установки pycron:"

#: ../src/fwbackups.glade.h:178
msgid "<b>Windows-specific options</b>"
msgstr "<b>Параметры только для ОС Windows</b>"

#: ../src/fwbackups.glade.h:179
msgid "Click to reset \"Don't show me again\" messages"
msgstr "Нажмите для сброса сообщения \"Больше не показывать\""

#: ../src/fwbackups.glade.h:180
msgid "Configure Set"
msgstr "Настроить набор"

#: ../src/fwbackups.glade.h:181
msgid "Paths"
msgstr "Пути"

#: ../src/fwbackups.glade.h:182
msgid "Destination Type:"
msgstr "Тип назначения:"

#: ../src/fwbackups.glade.h:183
msgid "Destination"
msgstr "Назначение"

#: ../src/fwbackups.glade.h:184
msgid "<b>Day(s) of the Week</b>"
msgstr "<b>Дни недели</b>"

#: ../src/fwbackups.glade.h:185
msgid "<b>Month(s)</b>"
msgstr "<b>Месяц(ы)</b>"

#: ../src/fwbackups.glade.h:186
msgid ""
"Please use the same syntax a crontab does to enter your settings.\n"
"<i>To obtain examples and more information on crontab syntax, click 'Help'.</i>"
msgstr "Используйте похожий синтаксис crontab при вводе ваших настроек.\n<i>Чтобы посмотреть примеры синтаксиса crontab нажмите 'Справка'.</i>"

#: ../src/fwbackups.glade.h:188
msgid ""
"No field verification is performed on a manual field to test if the input is valid.\n"
"Please make sure there are no errors."
msgstr "При ручном вводе не предусмотрена проверка на правильность заполнения полей.\nУбедитесь, что у вас нет ошибок."

#: ../src/fwbackups.glade.h:190
msgid " "
msgstr " "

#: ../src/fwbackups.glade.h:191
msgid "<b>Day(s) of Month</b>"
msgstr "<b>Дни месяца</b>"

#: ../src/fwbackups.glade.h:192
msgid "<b>Hour(s)</b>"
msgstr "<b>Час(ы)</b>"

#: ../src/fwbackups.glade.h:193
msgid "<b>Minute(s)</b>"
msgstr "<b>Минут(ы)</b>"

#: ../src/fwbackups.glade.h:194
msgid "Manual Configuration"
msgstr "Ручная настройка"

#: ../src/fwbackups.glade.h:195
msgid "All Months"
msgstr "Весь месяц"

#: ../src/fwbackups.glade.h:196
msgid "Only during:"
msgstr "Только в течении:"

#: ../src/fwbackups.glade.h:197
msgid "From:"
msgstr "С:"

#: ../src/fwbackups.glade.h:198
msgid ""
"January\n"
"February\n"
"March\n"
"April\n"
"May\n"
"June\n"
"July\n"
"August\n"
"September\n"
"October\n"
"November\n"
"December"
msgstr "Январь\nФевраль\nМарт\nАпрель\nМай\nИюнь\nИюль\nАвгуст\nСентябрь\nОктябрь\nНоябрь\nДекабрь"

#: ../src/fwbackups.glade.h:210
msgid "To:"
msgstr "До:"

#: ../src/fwbackups.glade.h:211
msgid "<b>Months</b>"
msgstr "<b>Месяцы</b>"

#: ../src/fwbackups.glade.h:212
msgid "Only on:"
msgstr "Только в:"

#: ../src/fwbackups.glade.h:213
msgid "All days of the week"
msgstr "Все дни недели"

#: ../src/fwbackups.glade.h:214
msgid ""
"Sunday\n"
"Monday\n"
"Tuesday\n"
"Wednesday\n"
"Thurday\n"
"Friday\n"
"Saturday"
msgstr "Воскресенья\nПонедельника\nВторника\nСреды\nЧетверга\nПятницы\nСубботы"

#: ../src/fwbackups.glade.h:221
msgid ""
"Sundays\n"
"Mondays\n"
"Tuesdays\n"
"Wednesdays\n"
"Thurdays\n"
"Fridays\n"
"Saturdays"
msgstr "Воскресенье\nПонедельник\nВторник\nСреда\nЧетверг\nПятница\nСуббота"

#: ../src/fwbackups.glade.h:228
msgid "<b>Days of the week</b>"
msgstr "<b>Дни недели</b>"

#: ../src/fwbackups.glade.h:229
msgid "At:"
msgstr "В:"

#: ../src/fwbackups.glade.h:230
msgid "All Hours"
msgstr "Каждый час"

#: ../src/fwbackups.glade.h:231
msgid ""
"0 (12am)\n"
"1 (1am)\n"
"2 (2am)\n"
"3 (3am)\n"
"4 (4am)\n"
"5 (5am)\n"
"6 (6am)\n"
"7 (7am)\n"
"8 (8am)\n"
"9 (9am)\n"
"10 (10am)\n"
"11 (11am)\n"
"12 (Noon)\n"
"13 (1pm)\n"
"14 (2pm)\n"
"15 (3pm)\n"
"16 (4pm)\n"
"17 (5pm)\n"
"18 (6pm)\n"
"19 (7pm)\n"
"20 (8pm)\n"
"21 (9pm)\n"
"22 (10pm)\n"
"23 (11pm)"
msgstr "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23"

#: ../src/fwbackups.glade.h:255
msgid "<b>Hours</b>"
msgstr "<b>Часы</b>"

#: ../src/fwbackups.glade.h:256
msgid "Only at:"
msgstr "Только в:"

#: ../src/fwbackups.glade.h:257
msgid "All Minutes"
msgstr "Каждую минуту"

#: ../src/fwbackups.glade.h:258
msgid "<b>Minute</b>"
msgstr "<b>Минута</b>"

#: ../src/fwbackups.glade.h:259
msgid "Easy Configuration"
msgstr "Быстрая настройка"

#: ../src/fwbackups.glade.h:260
msgid ""
"<i>Tip: Your backup will run whenever <b>all</b> of the criteria below match"
" the system time and date.</i>"
msgstr "<i>Совет: Резервирование будет запущено при <b>каждом</b> совпадении параметров даты и времени системы.</i>"

#: ../src/fwbackups.glade.h:261
msgid "Times"
msgstr "Время"

#: ../src/fwbackups.glade.h:262
msgid "Backups are incremental"
msgstr "Использовать нарастающее резервирование"

#: ../src/fwbackups.glade.h:263
msgid "Set is enabled"
msgstr "Набор включен"

#: ../src/fwbackups.glade.h:264
msgid "Include subfolders"
msgstr "Включая вложенные папки"

#: ../src/fwbackups.glade.h:265
msgid "Number of old backups to keep:"
msgstr "Число сохраняемых старых резервных копий:"

#: ../src/fwbackups.glade.h:266
msgid ""
"<i>Tip: </i>0<i> makes a new backup always replace an older one.\n"
"This option is unavailable with incremental backups.</i>"
msgstr "<i>Совет: </i>0<i> будет заменять старые резервные копии новыми.\nЭтот параметр неприменим при инкрементном резервировании.</i>"

#: ../src/fwbackups.glade.h:268
msgid "Options (Simple)"
msgstr "Основные опции"

#: ../src/fwbackups.glade.h:269
msgid "Command to run before backup:"
msgstr "Команда для запуска перед резервированием:"

#: ../src/fwbackups.glade.h:270
msgid "Command to run after backup:"
msgstr "Команда для запуска после  резервирования:"

#: ../src/fwbackups.glade.h:271
msgid ""
"<i>Tip: The following tokens may be used in the commands:\n"
"[destination], [set], [date], [backup], [remote_host], [remote_port], [remote_username], [remote_password]\n"
"\n"
"For a description of each, see the user manual.</i>"
msgstr "<i>Совет: Следующие маркеры могут быть использованы в командах:\n[destination], [set], [date], [backup], [remote_host], [remote_port], [remote_username], [remote_password]\n\nПо описанию каждого смотрите руководство пользователя.</i>"

#: ../src/fwbackups.glade.h:275
msgid "Options (Advanced)"
msgstr "Дополнительные опции"

#: ../src/fwbackups.glade.h:276
msgid "<b>Name:</b>"
msgstr "<b>Имя:</b>"

#: ../src/fwbackups.glade.h:277
msgid "fwbackups Initializing..."
msgstr "Инициализация fwbackups..."

#: ../src/fwbackups.glade.h:278
msgid " A feature-rich user backup program"
msgstr "Программа для резервного копирования с продвинутыми возможностями"

#: ../src/fwbackups.glade.h:279
msgid "<span size=\"xx-large\" weight=\"bold\">fwbackups</span>"
msgstr "<span size=\"xx-large\" weight=\"bold\">fwbackups</span>"

#: ../src/fwbackups.glade.h:280
msgid "<span size=\"small\">Please wait while fwbackups initializes.</span>"
msgstr "<span size=\"small\">Дождитесь инициализации fwbackups.</span>"

#: ../src/BugReport.glade.h:1 ../src/fwbackups/widgets.py:738
msgid "Bug Report"
msgstr "Отправить сообщение об ошибке"

#: ../src/BugReport.glade.h:2
msgid "<span size=\"larger\" weight=\"bold\">Sorry!</span>"
msgstr "<span size=\"larger\" weight=\"bold\">Извините!</span>"

#: ../src/BugReport.glade.h:3
msgid ""
"fwbackups has run into an unexpected error. You may continue using the "
"program, however it is recommended you quit and open fwbackups again."
msgstr "fwbackups запустился с неустановленной ошибкой. Вы можете продолжить использование программы, но мы рекомендуем закрыть её и попробовать запустить снова."

#: ../src/BugReport.glade.h:4
msgid "Traceback Here"
msgstr "Здесь Traceback"

#: ../src/BugReport.glade.h:5
msgid "_Details"
msgstr "_Подробности"

#: ../src/fwbackups/operations/__init__.py:60
msgid "Canceling the current operation!"
msgstr "Отменяется текущая операция!"

#: ../src/fwbackups/operations/__init__.py:64
#, python-format
msgid "Stopping process with ID %s"
msgstr "Остановка процесса с ID %s"

#: ../src/fwbackups/operations/__init__.py:67
#, python-format
msgid "Could not stop process %(a)s: %(b)s"
msgstr "Невозможно остановить процесс %(a)s: %(b)s"

#: ../src/fwbackups/operations/__init__.py:75
msgid "The operation has been cancelled."
msgstr "Операция была отменена."

#: ../src/fwbackups/operations/__init__.py:88
#, python-format
msgid "Error handling file `%s'"
msgstr "Ошибка обработки файла `%s'"

#: ../src/fwbackups/operations/__init__.py:89
#, python-format
msgid ""
"Output:\n"
"%s"
msgstr "Вывод:\n%s"

#: ../src/fwbackups/operations/__init__.py:94
#, python-format
msgid "Destination folder `%s' exists"
msgstr "Папка назначения `%s'  уже существует"

#: ../src/fwbackups/operations/__init__.py:99
#, python-format
msgid "Created destination folder `%s'"
msgstr "Создана папка назначения `%s'"

#: ../src/fwbackups/operations/__init__.py:101
#, python-format
msgid "The destination folder `%(a)s' could not be created: %(b)s"
msgstr "Папка назначения `%(a)s' не может быть создана: %(b)s"

#: ../src/fwbackups/operations/__init__.py:105
#, python-format
msgid ""
"You do not have read and write permissions on the destination `%s' - if you "
"backed up system files, this operation may fail."
msgstr "У вас нет прав на чтение/запись в назначении `%s - если вы выполните резервное копирование системных файлов, то эта операция может завершиться неудачей."

#: ../src/fwbackups/operations/backup.py:82
msgid "rpm - Package list"
msgstr "rpm - список пакетов"

#: ../src/fwbackups/operations/backup.py:101
msgid "Pacman - Package list"
msgstr "Pacman - список пакетов"

#: ../src/fwbackups/operations/backup.py:107
msgid "dpkg - Package list"
msgstr "dpkg - список пакетов"

#: ../src/fwbackups/operations/backup.py:117
msgid "Disk Information"
msgstr "Сведения о диске"

#: ../src/fwbackups/operations/backup.py:185
#, python-format
msgid "Attempting to connect to server %s..."
msgstr "Попытка соединения с сервером %s..."

#: ../src/fwbackups/operations/backup.py:196
msgid "Attempt to connect succeeded."
msgstr "Соединение прошло успешно."

#: ../src/fwbackups/operations/backup.py:199
msgid ""
"The backup destination was either not found or it cannot be written to due "
"to insufficient permissions."
msgstr "Назначение для резервирования либо не было найдено, либо не может быть записано из-за недостаточных прав."

#: ../src/fwbackups/operations/backup.py:203
#: ../src/fwbackups/operations/restore.py:88
msgid ""
"A connection was established, but authentication failed. Please verify the "
"username and password and try again."
msgstr "Соединение установлено, но аутенфикация не прошла. Проверьте имя пользователя и пароль."

#: ../src/fwbackups/operations/backup.py:208
#: ../src/fwbackups/operations/restore.py:93
#, python-format
msgid ""
"A connection to the server could not be established.\n"
"Error %(a)s: %(b)s"
msgstr "Соединение с сервером не может быть выполнено.\nОшибка %(a)s: %(b)s"

#: ../src/fwbackups/operations/backup.py:213
#: ../src/fwbackups/operations/restore.py:98
msgid ""
"A connection to the server has timed out. Please verify your settings and "
"try again."
msgstr "Соединение с сервером достигло таймаута. Пожалуйста, проверьте ваши настройки и попробуйте снова."

#: ../src/fwbackups/operations/backup.py:217
#: ../src/fwbackups/operations/restore.py:102
#, python-format
msgid ""
"A connection to the server could not be established because an error "
"occurred: %s"
msgstr "Соединение с сервером не установлено из-за ошибки: %s"

#: ../src/fwbackups/operations/backup.py:235
#: ../src/fwbackups/operations/backup.py:276
#: ../src/fwbackups/operations/backup.py:321
#, python-format
msgid ""
"Using %s on Windows: Cancel function will only take effect after a path has "
"been completed."
msgstr "Используйте %s в Windows: Функция отмены будет иметь эффект только после завершения пути."

#. let's deal with real paths
#: ../src/fwbackups/operations/backup.py:241
#: ../src/fwbackups/operations/backup.py:282
#: ../src/fwbackups/operations/backup.py:292
#: ../src/fwbackups/operations/backup.py:327
#: ../src/fwbackups/operations/backup.py:337
#: ../src/fwbackups/operations/backup.py:375
#: ../src/fwbackups/operations/backup.py:387
#, python-format
msgid "Backing up path %(a)i/%(b)i: %(c)s"
msgstr "Резервировать путь %(a)i/%(b)i: %(c)s"

#: ../src/fwbackups/operations/backup.py:249
#, python-format
msgid "Running command: nice -n %(a)i %(b)s '%(c)s'"
msgstr "Запуск команды: nice -n %(a)i %(b)s '%(c)s'"

#: ../src/fwbackups/operations/backup.py:252
#: ../src/fwbackups/operations/backup.py:297
#: ../src/fwbackups/operations/backup.py:342
#: ../src/fwbackups/operations/backup.py:394
#: ../src/fwbackups/operations/backup.py:598
#, python-format
msgid "Starting subprocess with PID %s"
msgstr "Запуск подпроцесса с PID %s"

#: ../src/fwbackups/operations/backup.py:266
#: ../src/fwbackups/operations/backup.py:311
#: ../src/fwbackups/operations/backup.py:356
#: ../src/fwbackups/operations/backup.py:408
#, python-format
msgid "Subprocess with PID %(a)s exited with status %(b)s"
msgstr "Подпроцесс с PID %(a)s завершился со статусом %(b)s"

#: ../src/fwbackups/operations/backup.py:271
#: ../src/fwbackups/operations/backup.py:316
#: ../src/fwbackups/operations/backup.py:361
#: ../src/fwbackups/operations/backup.py:413
#: ../src/fwbackups/operations/backup.py:615
#, python-format
msgid "Process exited with status %(a)s. Errors: %(b)s"
msgstr "Процесс завершен со статусом %(a)s. Ошибка: %(b)s"

#: ../src/fwbackups/operations/backup.py:284
#: ../src/fwbackups/operations/backup.py:329
#, python-format
msgid "Adding path `%s' to the archive"
msgstr "Добавление пути `%s' в архив"

#: ../src/fwbackups/operations/backup.py:291
#: ../src/fwbackups/operations/backup.py:336
#, python-format
msgid ""
"Using %s: Must backup all paths at once - Progress notification will be "
"disabled."
msgstr "Используйте %s: Должно зарезервировать все пути за раз - вывод прогресса операции отключен."

#: ../src/fwbackups/operations/backup.py:293
#: ../src/fwbackups/operations/backup.py:338
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s"
msgstr "Запуск команды: nice -n %(a)i %(b)s %(c)s"

#: ../src/fwbackups/operations/backup.py:377
#, python-format
msgid ""
"Path %s is missing or cannot be read and will be excluded from the backup."
msgstr "Путь %s отсутствует или не может быть прочитан и будет исключен из резервирования."

#: ../src/fwbackups/operations/backup.py:391
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s '%(d)s'"
msgstr "Запуск команды: nice -n %(a)i %(b)s %(c)s '%(d)s'"

#: ../src/fwbackups/operations/backup.py:419
msgid "Sending files to server via SFTP"
msgstr "Посылка файлов на сервер через SFTP"

#: ../src/fwbackups/operations/backup.py:429
msgid "Could not send file(s) or folder to server:"
msgstr "Невозможно послать файл(ы) или папку на сервер:"

#: ../src/fwbackups/operations/backup.py:443
msgid "This function is designed to be subclassed"
msgstr "Эта функция спроектирована как подкласс"

#: ../src/fwbackups/operations/backup.py:452
msgid "Starting one-time backup operation"
msgstr "Запуск разового резервирования"

#: ../src/fwbackups/operations/backup.py:457
msgid "OneTime"
msgstr "Разовое"

#: ../src/fwbackups/operations/backup.py:471
#: ../src/fwbackups/operations/backup.py:679
msgid "There are no paths to backup!"
msgstr "Нет путей для резервирования!"

#: ../src/fwbackups/operations/backup.py:489
#: ../src/fwbackups/operations/backup.py:694
#, python-format
msgid "`%s' exists and will be overwritten."
msgstr "`%s' существует и будет перезаписан."

#. All done!
#: ../src/fwbackups/operations/backup.py:509
msgid "Finished one-time backup"
msgstr "Завершено разовое резервирование"

#: ../src/fwbackups/operations/backup.py:523
#, python-format
msgid "Starting automatic backup operation of set `%s'"
msgstr "Запуск автоматического резервирования для набора `%s'"

#. Execute the command
#: ../src/fwbackups/operations/backup.py:595
#, python-format
msgid "Executing '%s' command"
msgstr "Выполнение команды '%s'"

#: ../src/fwbackups/operations/backup.py:614
msgid "Command returned with a non-zero exit status!"
msgstr "Команда вернула ненулевой статус завершения!"

#: ../src/fwbackups/operations/backup.py:640
#, python-format
msgid "Removing old backup `%(a)s' on %(b)s"
msgstr "Удаление старой резервной копии: `%(a)s' на %(b)s"

#: ../src/fwbackups/operations/backup.py:647
#: ../src/fwbackups/operations/backup.py:660
#, python-format
msgid "Removing old backup `%s'"
msgstr "Удаление старой резервной копии `%s'"

#. oldIncrementalBackup = rsync
#: ../src/fwbackups/operations/backup.py:653
#, python-format
msgid "Moving  `%s' to `%s'"
msgstr "Перемещение `%s' в `%s'"

#. source = is not a rsync backup - remove it and start fresh
#: ../src/fwbackups/operations/backup.py:656
#, python-format
msgid "`%s' is not an rsync backup - removing."
msgstr "`%s' не является резервной копией rsync - удаляем."

#. All done!
#: ../src/fwbackups/operations/backup.py:741
#, python-format
msgid "Finished automatic backup operation of set '%s'"
msgstr "Завершено автоматическое резервирование для набора '%s'"

#: ../src/fwbackups/operations/restore.py:42
msgid "Starting restore operation"
msgstr "Старт операции восстановления"

#. check if server settings are OK
#: ../src/fwbackups/operations/restore.py:71
msgid "Attempting to connect to server"
msgstr "Попытка соединения с сервером"

#: ../src/fwbackups/operations/restore.py:84
msgid ""
"The restore source was either not found or it cannot be read due to "
"insufficient permissions."
msgstr "Восстанавливаемый источник либо не был найден, либо не может быть прочитан из-за недостаточных прав."

#: ../src/fwbackups/operations/restore.py:116
msgid "Receiving files from server"
msgstr "Приём файлов с сервера"

#: ../src/fwbackups/operations/restore.py:127
#, python-format
msgid "Could not receive file from server: %s"
msgstr "Невозможно принять файлы с сервера: %s"

#. We are dealing with a remote folder - our job here is done
#. Either that or an error was encountered above
#. All done!
#: ../src/fwbackups/operations/restore.py:132
#: ../src/fwbackups/operations/restore.py:177
msgid "Finished restore operation"
msgstr "Операция восстановления закончена"

#. oops, something is up
#: ../src/fwbackups/operations/restore.py:144
#, python-format
msgid "Source `%s' is not a file or folder!"
msgstr "Источник `%s' не файл или папка!"

#. oops, something is up
#: ../src/fwbackups/operations/restore.py:153
#, python-format
msgid "Source `%s' is not an archive!"
msgstr "Источник `%s' не архив!"

#: ../src/fwbackups/operations/restore.py:157
#, python-format
msgid "Source `%s' is not a folder"
msgstr "Источник `%s' не папка"

#: ../src/fwbackups/operations/restore.py:173
#, python-format
msgid "Traceback: %s"
msgstr "Traceback: %s"

#: ../src/fwbackups/config.py:50
#, python-format
msgid "Could not create configuration folder `%s':"
msgstr "Не возможно создать папку конфигурации `%s':"

#: ../src/fwbackups/config.py:57
#, python-format
msgid "You do not have read and write permissions on folder `%s'."
msgstr "У вас нет прав на чтение/запись папки `%s'."

#: ../src/fwbackups/config.py:115
#, python-format
msgid "Key %s of is not a dictionary of options"
msgstr "Ключ %s не в словаре вариантов"

#: ../src/fwbackups/config.py:333
#, python-format
msgid "Set '%s' failed to pass section validation"
msgstr "Набор '%s'  не прошёл проверку секции"

#: ../src/fwbackups/config.py:336
#, python-format
msgid "'%(a)s' is not a set configuration file."
msgstr "'%(a)s' не является файлом конфигурации набора."

#: ../src/fwbackups/config.py:340
#, python-format
msgid ""
"Configuration section 'General' in the set configuration '%s' failed to "
"validate"
msgstr "Секция 'General' в файле конфигурации набора '%s' не прошла проверку"

#: ../src/fwbackups/config.py:343
#, python-format
msgid ""
"Configuration section 'Times' in the set configuration '%s' failed to "
"validate"
msgstr "Секция 'Time' в файле конфигурации набора '%s' не прошла проверку"

#: ../src/fwbackups/config.py:356
#, python-format
msgid "Unknown option key '%(a)s' present in set configuration '%(b)s'"
msgstr "Неизвестный ключ '%(a)s' в конфигурации набора  '%(b)s'"

#: ../src/fwbackups/config.py:361
#, python-format
msgid ""
"Configuration section 'Options' in set configuration '%(a)s' failed to "
"validate: Missing options '%(b)s'"
msgstr "Секция 'Options' в файле конфигурации набора '%(a)s' не прошла проверку: Пропущен параметр  '%(b)s'"

#: ../src/fwbackups/config.py:496
msgid "One-time configuration failed to pass section validation"
msgstr "Разовое резервирование не прошло проверку раздела"

#: ../src/fwbackups/config.py:499
#, python-format
msgid "'%(a)s' is not a one-time configuration file."
msgstr "'%(a)s' не является файлом конфигурации разового резервирования"

#: ../src/fwbackups/config.py:503
msgid ""
"Configuration section 'General' in the one-time configuration file failed to"
" validate"
msgstr "Секция 'General' файла конфигурации разового резервирования не прошла проверку"

#: ../src/fwbackups/config.py:515
#, python-format
msgid "Unknown option key '%s' present in one-time backup configuration file"
msgstr "Неверный параметр '%s'  в файле конфигурации разового резервирования"

#: ../src/fwbackups/config.py:520
#, python-format
msgid ""
"Configuration section 'Options' in the one-time backup configuration file "
"failed to validate: Missing options '%s'"
msgstr "Секция 'Options' файла конфигурации разового резервирования не прошла проверку: Отсутствует параметр '%s'"

#: ../src/fwbackups/config.py:623
msgid "Restore configuration failed to pass section validation"
msgstr "Конфигурация восстановления не прошла проверку секции"

#: ../src/fwbackups/config.py:626
#, python-format
msgid "'%(a)s' is not a restore configuration file."
msgstr "'%(a)s' не является файлом конфигурации восстановления"

#: ../src/fwbackups/config.py:630
msgid ""
"Configuration section 'General' in the restore configuration file failed to "
"validate"
msgstr "Секция 'General' файла конфигурации восстановления не прошла проверку"

#: ../src/fwbackups/config.py:640
#, python-format
msgid "Unknown option key '%s' present in restore configuration file"
msgstr "Неизвестный ключ '%s' в файле конфигурации восстановления"

#: ../src/fwbackups/config.py:645
#, python-format
msgid ""
"Configuration section 'Options' in the restore configuration file failed to "
"validate: Missing options '%s'"
msgstr "Секция 'Options' файла конфигурации восстановления не прошла проверку: Пропущен параметр '%s'"

#: ../src/fwbackups/config.py:737
msgid "Preferences failed to pass section validation"
msgstr "Файл настроек не прошел проверку секции"

#: ../src/fwbackups/config.py:740
#, python-format
msgid "'%(a)s' is not a fwbackups preferences file."
msgstr "'%(a)s' не является файлом настроек fwbackups."

#: ../src/fwbackups/config.py:744
msgid ""
"Configuration section 'General' in the preferences file failed to validate"
msgstr "Секция 'General' файла настроек не прошла проверку"

#: ../src/fwbackups/config.py:755
#, python-format
msgid "Unknown option key '%s' present in preferences file"
msgstr "Неизвестный ключ '%s' обнаружен в файле настроек"

#: ../src/fwbackups/config.py:760
#, python-format
msgid ""
"Configuration section 'Options' in the preferences file failed to validate: "
"Missing options '%s'"
msgstr "Секция 'Options' файла настроек не прошла проверку: Пропущен параметр '%s'"

#: ../src/fwbackups/config.py:854
msgid "Unable to clean user crontab!"
msgstr "Невозможно очистить crontab пользователя!"

#: ../src/fwbackups/cron.py:135
#, python-format
msgid "Could not locate the pycron or the sample pycron configuration in %s"
msgstr "Не обнаружен pycron или пример файла конфигурации pycron в %s"

#: ../src/fwbackups/cron.py:144
#, python-format
msgid "Could not locate the pycron or the sample pycron crontab file in %s"
msgstr "Не обнаружен pycron или пример файла pycron crontab в %s"

#: ../src/fwbackups/fwlogger.py:70
#, python-format
msgid "Could not set up the logger: %s"
msgstr "Невозможно настроить журналирование: %s"

#: ../src/fwbackups/sftp.py:212
#, python-format
msgid "`%s' is not a file, folder or link! Skipping."
msgstr "`%s' это не файл, папка или ссылка! Пропускается."

#: ../src/fwbackups/sftp.py:217
msgid "Could not copy some files due to errors:"
msgstr "Невозможно скопировать некоторые файлы из-за ошибки:"

#: ../src/fwbackups/shutil_modded.py:131
#, python-format
msgid "`%s' isn't a file, folder or link! Skipping."
msgstr "`%s' это не файл, папка или ссылка! Пропускается."

#: ../src/fwbackups/shutil_modded.py:142
msgid "Couldn't copy some files due to errors:"
msgstr "Невозможно скопировать некоторые файлы из-за ошибки:"

#: ../src/fwbackups/widgets.py:153 ../src/fwbackups/widgets.py:198
msgid "CRITICAL"
msgstr "КРИТИЧНО"

#: ../src/fwbackups/widgets.py:153 ../src/fwbackups/widgets.py:198
msgid "ERROR"
msgstr "ОШИБКА"

#: ../src/fwbackups/widgets.py:155 ../src/fwbackups/widgets.py:200
msgid "WARNING"
msgstr "ПРЕДУПРЕЖДЕНИЕ"

#: ../src/fwbackups/widgets.py:168 ../src/fwbackups/widgets.py:193
msgid "Previous log messages"
msgstr "Предыдущие сообщения журнала"

#: ../src/fwbackups/widgets.py:172 ../src/fwbackups/widgets.py:207
msgid "No previous log messages to display"
msgstr "Нет сообщений предыдущего журнала для отображения"

#: ../src/fwbackups/widgets.py:174 ../src/fwbackups/widgets.py:184
msgid "Current session's log messages"
msgstr "Журнал сообщений текущей сессии"

#: ../src/fwbackups/widgets.py:536
msgid "Access"
msgstr "Доступ"

#: ../src/fwbackups/widgets.py:542
msgid "Path"
msgstr "Путь"

#: ../src/fwbackups/widgets.py:618
msgid "Choose file(s)"
msgstr "Выберите файл(ы)"

#: ../src/fwbackups/widgets.py:629
msgid "Choose folder(s)"
msgstr "Выберите папку(и)"

#: ../src/fwbackups/widgets.py:660
msgid "Please select a path before choosing an action."
msgstr "Выберите путь перед заданием действия."

#: ../src/fwbackups/widgets.py:696
msgid "Export"
msgstr "Экспорт"

#: ../src/fwbackups/widgets.py:702
msgid "Set"
msgstr "Набор"
